
interface SeedMerma {
  name: string;
  porcentaje: number;
  precioAnterior: number;
  precioActual: number;
  unidadMedida: 'miligramos' | 'gramos' | 'kilo' | 'mililitros' | 'litro' | 'unidad';

  
}

export const mermas: SeedMerma[] = [
  {name: 'Banana',porcentaje: 35, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Banana',porcentaje: 35, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Cereza', porcentaje: 8, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Ciruela', porcentaje: 15, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Fresa', porcentaje: 4, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Granada', porcentaje: 45, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Higo', porcentaje: 10, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Kiwi', porcentaje: 10, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Lima', porcentaje: 24, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Limón', porcentaje: 36, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Limón (jugo)', porcentaje: 80, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Manzana', porcentaje: 12.50, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Melón', porcentaje: 35, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Naranja', porcentaje: 32, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pera', porcentaje: 18, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Piña', porcentaje: 25, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Plátano', porcentaje: 35, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Sandía', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Tomate', porcentaje: 15, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Tomate cherry', porcentaje: 5, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Carne de cordero', porcentaje: 20, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Carrillada', porcentaje: 50, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Cerdo (carne magra)', porcentaje: 18, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Cerdo (costillas)', porcentaje: 33, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Codorniz', porcentaje: 28, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Conejo', porcentaje: 20, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Cordero (costillas)', porcentaje: 24, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Cordero (paleta)', porcentaje: 20, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Filete de cerdo', porcentaje: 5, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Lomo de cerdo', porcentaje: 20, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pato (asado)', porcentaje: 35, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pavo (asado)', porcentaje: 35, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pechuga de pavo', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pechuga de pollo', porcentaje: 37, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pollo', porcentaje: 26, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pollo (asado)', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Rabo de Buey', porcentaje: 67.50, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Vacuno (guiso)', porcentaje: 27, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Vacuno (lomo)', porcentaje: 41, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Acelga', porcentaje: 40, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Aguacate', porcentaje: 25, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Albahaca', porcentaje: 40, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Alcachofa', porcentaje: 80, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Apio', porcentaje: 20, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Berenjena', porcentaje: 13, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Brócoli', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Calabacín', porcentaje: 11, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Cebolla', porcentaje: 15, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Champiñon', porcentaje: 10, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Cilantro', porcentaje: 50, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Col blanca', porcentaje: 15, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Col de Bruselas', porcentaje: 15, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Coliflor', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Espárrago blanco', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Jengibre', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Judía verde', porcentaje: 7, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Lechuga', porcentaje: 15, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Manzana', porcentaje: 34, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Papa pelada a mano', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Papa pelada a maquina', porcentaje: 25, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Papaya', porcentaje: 15, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pepino', porcentaje: 5, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Puerro', porcentaje: 20, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Zanahoria', porcentaje: 29.50, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pimiento amarillo', porcentaje: 20, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pimiento rojo', porcentaje: 20, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pimiento verde', porcentaje: 20, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Almeja', porcentaje: 70, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Almeja chica', porcentaje: 80, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Anguila', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Bacalao fresco', porcentaje: 50, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Bonito', porcentaje: 29, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Calamar', porcentaje: 20, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Camarón grande', porcentaje: 15, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Camarón seco', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Cangrejo', porcentaje: 85, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Langosta', porcentaje: 75, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Lenguado', porcentaje: 50, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Mejillón', porcentaje: 55, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Merluza', porcentaje: 20, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Pulpo', porcentaje: 12, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Raya', porcentaje: 37, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Rodaballo', porcentaje: 35, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Salmón', porcentaje: 19, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Salmonete', porcentaje: 18, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Sardina', porcentaje: 46, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Sepia', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' },
    {name: 'Trucha', porcentaje: 30, precioAnterior: 1 ,precioActual:1, unidadMedida: 'unidad' }
];
