
interface SeedMerma {
  name: string;
  porcentaje: number;
  precio: number;
  unidadMedida: 'miligramos' | 'gramos' | 'kilo' | 'mililitros' | 'litro' | 'unidad';

  
}

export const mermas: SeedMerma[] = [
  {name: 'Banana',porcentaje: 35, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Banana',porcentaje: 35, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Cereza', porcentaje: 8, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Ciruela', porcentaje: 15, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Fresa', porcentaje: 4, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Granada', porcentaje: 45, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Higo', porcentaje: 10, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Kiwi', porcentaje: 10, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Lima', porcentaje: 24, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Limón', porcentaje: 36, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Limón (jugo)', porcentaje: 80, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Manzana', porcentaje: 12.50, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Melón', porcentaje: 35, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Naranja', porcentaje: 32, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pera', porcentaje: 18, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Piña', porcentaje: 25, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Plátano', porcentaje: 35, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Sandía', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Tomate', porcentaje: 15, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Tomate cherry', porcentaje: 5, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Carne de cordero', porcentaje: 20, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Carrillada', porcentaje: 50, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Cerdo (carne magra)', porcentaje: 18, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Cerdo (costillas)', porcentaje: 33, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Codorniz', porcentaje: 28, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Conejo', porcentaje: 20, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Cordero (costillas)', porcentaje: 24, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Cordero (paleta)', porcentaje: 20, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Filete de cerdo', porcentaje: 5, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Lomo de cerdo', porcentaje: 20, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pato (asado)', porcentaje: 35, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pavo (asado)', porcentaje: 35, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pechuga de pavo', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pechuga de pollo', porcentaje: 37, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pollo', porcentaje: 26, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pollo (asado)', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Rabo de Buey', porcentaje: 67.50, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Vacuno (guiso)', porcentaje: 27, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Vacuno (lomo)', porcentaje: 41, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Acelga', porcentaje: 40, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Aguacate', porcentaje: 25, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Albahaca', porcentaje: 40, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Alcachofa', porcentaje: 80, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Apio', porcentaje: 20, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Berenjena', porcentaje: 13, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Brócoli', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Calabacín', porcentaje: 11, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Cebolla', porcentaje: 15, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Champiñon', porcentaje: 10, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Cilantro', porcentaje: 50, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Col blanca', porcentaje: 15, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Col de Bruselas', porcentaje: 15, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Coliflor', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Espárrago blanco', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Jengibre', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Judía verde', porcentaje: 7, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Lechuga', porcentaje: 15, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Manzana', porcentaje: 34, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Papa pelada a mano', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Papa pelada a maquina', porcentaje: 25, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Papaya', porcentaje: 15, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pepino', porcentaje: 5, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Puerro', porcentaje: 20, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Zanahoria', porcentaje: 29.50, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pimiento amarillo', porcentaje: 20, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pimiento rojo', porcentaje: 20, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pimiento verde', porcentaje: 20, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Almeja', porcentaje: 70, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Almeja chica', porcentaje: 80, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Anguila', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Bacalao fresco', porcentaje: 50, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Bonito', porcentaje: 29, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Calamar', porcentaje: 20, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Camarón grande', porcentaje: 15, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Camarón seco', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Cangrejo', porcentaje: 85, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Langosta', porcentaje: 75, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Lenguado', porcentaje: 50, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Mejillón', porcentaje: 55, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Merluza', porcentaje: 20, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Pulpo', porcentaje: 12, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Raya', porcentaje: 37, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Rodaballo', porcentaje: 35, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Salmón', porcentaje: 19, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Salmonete', porcentaje: 18, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Sardina', porcentaje: 46, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Sepia', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' },
    {name: 'Trucha', porcentaje: 30, precio: 1000 , unidadMedida: 'miligramos' }
];
