

interface SeedMerma {
  name: string;
  porcentaje: number;
  precioActual: number;
  unidadMedida: 'miligramos' | 'gramos' | 'kilo' | 'mililitros' | 'litro' | 'unidad';
  cantidad: number;
  precioUnitarioActual: number;
  productId?: string;
  
}

export const mermas: SeedMerma[] = [
  {name: 'Banana',porcentaje: 35,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Cereza', porcentaje: 8,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Ciruela', porcentaje: 15,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Fresa', porcentaje: 4,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Granada', porcentaje: 45,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Higo', porcentaje: 10,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Kiwi', porcentaje: 10,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Lima', porcentaje: 24,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Limón', porcentaje: 36,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Limón (jugo)', porcentaje: 80,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Manzana', porcentaje: 12.50,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Melón', porcentaje: 35,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Naranja', porcentaje: 32,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pera', porcentaje: 18,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Piña', porcentaje: 25,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Plátano', porcentaje: 35,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Sandía', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Tomate', porcentaje: 15,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Tomate cherry', porcentaje: 5,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Carne de cordero', porcentaje: 20,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Carrillada', porcentaje: 50,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Cerdo (carne magra)', porcentaje: 18,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Cerdo (costillas)', porcentaje: 33,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Codorniz', porcentaje: 28,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Conejo', porcentaje: 20,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Cordero (costillas)', porcentaje: 24,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Cordero (paleta)', porcentaje: 20,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Filete de cerdo', porcentaje: 5,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Lomo de cerdo', porcentaje: 20,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pato (asado)', porcentaje: 35,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pavo (asado)', porcentaje: 35,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pechuga de pavo', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pechuga de pollo', porcentaje: 37,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pollo', porcentaje: 26,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pollo (asado)', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Rabo de Buey', porcentaje: 67.50,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Vacuno (guiso)', porcentaje: 27,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Vacuno (lomo)', porcentaje: 41,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Acelga', porcentaje: 40,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Aguacate', porcentaje: 25,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Albahaca', porcentaje: 40,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Alcachofa', porcentaje: 80,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Apio', porcentaje: 20,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Berenjena', porcentaje: 13,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Brócoli', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Calabacín', porcentaje: 11,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Cebolla', porcentaje: 15,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Champiñon', porcentaje: 10,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Cilantro', porcentaje: 50,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Col blanca', porcentaje: 15,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Col de Bruselas', porcentaje: 15,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Coliflor', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Espárrago blanco', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Jengibre', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Judía verde', porcentaje: 7,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Lechuga', porcentaje: 15,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Manzana', porcentaje: 34,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Papa pelada a mano', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Papa pelada a maquina', porcentaje: 25,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Papaya', porcentaje: 15,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pepino', porcentaje: 5,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Puerro', porcentaje: 20,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Zanahoria', porcentaje: 29.50,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pimiento amarillo', porcentaje: 20,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pimiento rojo', porcentaje: 20,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pimiento verde', porcentaje: 20,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Almeja', porcentaje: 70,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Almeja chica', porcentaje: 80,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Anguila', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Bacalao fresco', porcentaje: 50,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Bonito', porcentaje: 29,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Calamar', porcentaje: 20,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Camarón grande', porcentaje: 15,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Camarón seco', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Cangrejo', porcentaje: 85,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Langosta', porcentaje: 75,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Lenguado', porcentaje: 50,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Mejillón', porcentaje: 55,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Merluza', porcentaje: 20,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Pulpo', porcentaje: 12,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Raya', porcentaje: 37,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Rodaballo', porcentaje: 35,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Salmón', porcentaje: 19,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Salmonete', porcentaje: 18,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Sardina', porcentaje: 46,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Sepia', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' },
    {name: 'Trucha', porcentaje: 30,cantidad: 0,precioActual:1,precioUnitarioActual:1, unidadMedida: 'unidad', productId:' ' }
];
